# Generated by Django 4.0 on 2022-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_url_urlmapper_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapper',
            name='shortened_url_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
