# Generated by Django 4.0 on 2022-11-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_urlmapper_shortened_url_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapper',
            old_name='shortened_url_hash',
            new_name='shortened_url',
        ),
    ]
